/**
 * SmartBus Core Data Layer
 * Standardized Schema & Entities
 * 
 * 1. USERS: UserID, Name, Email, Role, Contact, Department, Year, DigitalPassID
 * 2. BUSES: BusID, BusNo, Capacity, driverId, routeId, status, model, fuelType, currentOccupancy
 * 3. DRIVERS: DriverID, Name, Contact, assignedBusId, assignedRouteId, status, licenseNumber, shift, rating
 * 4. ROUTES: RouteID, StartPoint, EndPoint, routeName, stops, distance, estimatedDuration, schedules
 * 5. TRACKING: BusID, Latitude, Longitude, speed, timestamp, currentStop, nextStop, eta, isLive
 * 6. COMPLAINTS: complaintId, userId, busId, subject, category, description, status, createdAt, adminRemark
 * 7. TRIPS: tripId, busId, driverId, routeId, startTime, endTime, status, passengers, currentStop, nextStop
 */

export const INITIAL_USERS = [
  {
    UserID: 'user_student_1',
    id: 'user_student_1',
    Name: 'Alex Johnson',
    name: 'Alex Johnson',
    Email: 'student@smartbus.edu',
    email: 'student@smartbus.edu',
    Role: 'student',
    role: 'student',
    Contact: '+91 98290 12345',
    phone: '+91 98290 12345',
    studentId: 'STU-2026-001',
    department: 'Computer Science & Engineering',
    year: '3rd Year',
    digitalPassId: 'SB-STU-2026-001',
  },
  {
    UserID: 'user_student_2',
    id: 'user_student_2',
    Name: 'Priya Sharma',
    name: 'Priya Sharma',
    Email: 'priya@smartbus.edu',
    email: 'priya@smartbus.edu',
    Role: 'student',
    role: 'student',
    Contact: '+91 98291 99887',
    phone: '+91 98291 99887',
    studentId: 'STU-2026-002',
    department: 'Electrical Engineering',
    year: '2nd Year',
    digitalPassId: 'SB-STU-2026-002',
  },
  {
    UserID: 'drv_1',
    id: 'drv_1',
    DriverID: 'DRV-101',
    driverId: 'DRV-101',
    Name: 'Ramesh Sharma',
    name: 'Ramesh Sharma',
    Email: 'driver@smartbus.edu',
    email: 'driver@smartbus.edu',
    Role: 'driver',
    role: 'driver',
    Contact: '+91 94140 67890',
    phone: '+91 94140 67890',
    assignedBusId: 'bus_101',
    assignedBusNumber: 'BUS-101',
    assignedRouteId: 'route_1',
    assignedRouteName: 'Udaipur City Station Express (R-01)',
    shift: 'Morning',
    status: 'On Trip',
    tripsToday: 3,
    rating: '4.9 ⭐',
    licenseNumber: 'RJ-27-2018-00912',
  },
  {
    UserID: 'drv_2',
    id: 'drv_2',
    DriverID: 'DRV-102',
    driverId: 'DRV-102',
    Name: 'Sunil Verma',
    name: 'Sunil Verma',
    Email: 'sunil@smartbus.edu',
    email: 'sunil@smartbus.edu',
    Role: 'driver',
    role: 'driver',
    Contact: '+91 98281 44321',
    phone: '+91 98281 44321',
    assignedBusId: 'bus_102',
    assignedBusNumber: 'BUS-102',
    assignedRouteId: 'route_2',
    assignedRouteName: 'Fateh Sagar & MLSU Corridor (R-02)',
    shift: 'Morning',
    status: 'On Trip',
    tripsToday: 2,
    rating: '4.8 ⭐',
    licenseNumber: 'RJ-27-2019-01124',
  },
  {
    UserID: 'drv_3',
    id: 'drv_3',
    DriverID: 'DRV-103',
    driverId: 'DRV-103',
    Name: 'Mahesh Joshi',
    name: 'Mahesh Joshi',
    Email: 'mahesh@smartbus.edu',
    email: 'mahesh@smartbus.edu',
    Role: 'driver',
    role: 'driver',
    Contact: '+91 94142 88711',
    phone: '+91 94142 88711',
    assignedBusId: '',
    assignedBusNumber: 'Unassigned',
    assignedRouteId: '',
    assignedRouteName: 'None',
    shift: 'Evening',
    status: 'Available',
    tripsToday: 1,
    rating: '4.7 ⭐',
    licenseNumber: 'RJ-27-2020-00854',
  },
  {
    UserID: 'drv_4',
    id: 'drv_4',
    DriverID: 'DRV-104',
    driverId: 'DRV-104',
    Name: 'Vikram Singh',
    name: 'Vikram Singh',
    Email: 'vikram@smartbus.edu',
    email: 'vikram@smartbus.edu',
    Role: 'driver',
    role: 'driver',
    Contact: '+91 97830 55192',
    phone: '+91 97830 55192',
    assignedBusId: '',
    assignedBusNumber: 'Unassigned',
    assignedRouteId: '',
    assignedRouteName: 'None',
    shift: 'Full Day',
    status: 'Available',
    tripsToday: 0,
    rating: '5.0 ⭐',
    licenseNumber: 'RJ-27-2021-00431',
  },
  {
    UserID: 'user_admin_1',
    id: 'user_admin_1',
    Name: 'Dr. Arthur Vance (Fleet Director)',
    name: 'Dr. Arthur Vance (Fleet Director)',
    Email: 'admin@smartbus.edu',
    email: 'admin@smartbus.edu',
    Role: 'admin',
    role: 'admin',
    Contact: '+91 94141 00000',
    phone: '+91 94141 00000',
    department: 'Transport Operations Control',
  },
];

export const INITIAL_DRIVERS = INITIAL_USERS.filter((u) => u.Role === 'driver' || u.role === 'driver');

export const INITIAL_ROUTES = [
  {
    RouteID: 'route_1',
    id: 'route_1',
    StartPoint: 'Udaipur Railway Station',
    startPoint: 'Udaipur Railway Station',
    EndPoint: 'Sukhadia Circle Terminal',
    destination: 'Sukhadia Circle Terminal',
    routeName: 'Udaipur City Station Express (R-01)',
    distance: '8.5 km',
    totalDistance: '8.5 km',
    estimatedDuration: '26 mins',
    status: 'Active',
    schedules: ['07:30 AM', '08:15 AM', '09:00 AM', '01:30 PM', '04:30 PM', '05:45 PM'],
    stops: [
      { id: 's1', sequenceOrder: 1, name: 'Udaipur Railway Station Depot', lat: 24.5714, lng: 73.6974, estimatedTime: '08:15 AM' },
      { id: 's2', sequenceOrder: 2, name: 'Surajpole Circle Flyover', lat: 24.5780, lng: 73.6990, estimatedTime: '08:22 AM' },
      { id: 's3', sequenceOrder: 3, name: 'Delhi Gate Central Stop', lat: 24.5840, lng: 73.6940, estimatedTime: '08:28 AM' },
      { id: 's4', sequenceOrder: 4, name: 'Hathipole Market Bus Stop', lat: 24.5880, lng: 73.6870, estimatedTime: '08:34 AM' },
      { id: 's5', sequenceOrder: 5, name: 'Chetak Circle Junction', lat: 24.5930, lng: 73.6890, estimatedTime: '08:39 AM' },
      { id: 's6', sequenceOrder: 6, name: 'Sukhadia Circle Terminal', lat: 24.6030, lng: 73.6910, estimatedTime: '08:45 AM' }
    ],
  },
  {
    RouteID: 'route_2',
    id: 'route_2',
    StartPoint: 'Fateh Sagar Lake Promenade',
    startPoint: 'Fateh Sagar Lake Promenade',
    EndPoint: 'MLSU University Main Gate',
    destination: 'MLSU University Main Gate',
    routeName: 'Fateh Sagar & MLSU Corridor (R-02)',
    distance: '12.4 km',
    totalDistance: '12.4 km',
    estimatedDuration: '35 mins',
    status: 'Active',
    schedules: ['08:00 AM', '08:45 AM', '12:15 PM', '03:30 PM', '05:15 PM'],
    stops: [
      { id: 's10', sequenceOrder: 1, name: 'Fateh Sagar Lake Promenade', lat: 24.6010, lng: 73.6760, estimatedTime: '08:30 AM' },
      { id: 's11', sequenceOrder: 2, name: 'Saheliyon Ki Bari Heritage Garden', lat: 24.6060, lng: 73.6840, estimatedTime: '08:38 AM' },
      { id: 's12', sequenceOrder: 3, name: 'Panchwati Residential Stop', lat: 24.6010, lng: 73.6920, estimatedTime: '08:46 AM' },
      { id: 's13', sequenceOrder: 4, name: 'MLSU University Main Gate', lat: 24.5950, lng: 73.7180, estimatedTime: '09:05 AM' },
    ],
  },
  {
    RouteID: 'route_3',
    id: 'route_3',
    StartPoint: 'Sector 4 Community Hub',
    startPoint: 'Sector 4 Community Hub',
    EndPoint: 'IT Park Techno Tower',
    destination: 'IT Park Techno Tower',
    routeName: 'Hiran Magri & Tech Corridor (R-03)',
    distance: '10.2 km',
    totalDistance: '10.2 km',
    estimatedDuration: '28 mins',
    status: 'Active',
    schedules: ['07:45 AM', '08:30 AM', '01:00 PM', '05:00 PM'],
    stops: [
      { id: 's20', sequenceOrder: 1, name: 'Sector 4 Community Hub', lat: 24.5600, lng: 73.7150, estimatedTime: '08:00 AM' },
      { id: 's21', sequenceOrder: 2, name: 'Goverdhan Vilas Circle', lat: 24.5500, lng: 73.7050, estimatedTime: '08:12 AM' },
      { id: 's22', sequenceOrder: 3, name: 'IT Park Techno Tower', lat: 24.5420, lng: 73.7250, estimatedTime: '08:28 AM' },
    ],
  },
];

export const INITIAL_BUSES = [
  {
    BusID: 'bus_101',
    id: 'bus_101',
    BusNo: 'BUS-101',
    busNumber: 'BUS-101',
    Capacity: 52,
    capacity: 52,
    registrationNumber: 'RJ-27-PA-4081',
    model: 'Tata Starbus Ultra 52S',
    fuelType: 'Diesel',
    driverId: 'drv_1',
    driverName: 'Ramesh Sharma',
    routeId: 'route_1',
    routeName: 'Udaipur City Station Express (R-01)',
    shift: 'Morning',
    status: 'In Transit',
    timingStatus: 'In Transit',
    departureTime: '08:15 AM',
    expectedArrival: '08:45 AM',
    scheduledDeparture: '08:15 AM',
    delayMinutes: 0,
    isLive: true,
    currentOccupancy: 38,
    speed: 34.5,
    avgSpeed: 28.0,
    currentLat: 24.5880,
    currentLng: 73.6870,
    currentStop: 'Delhi Gate Central Stop',
    nextStop: 'Hathipole Market Bus Stop',
    etaMinutes: 4,
    lastUpdated: new Date().toISOString(),
  },
  {
    BusID: 'bus_102',
    id: 'bus_102',
    BusNo: 'BUS-102',
    busNumber: 'BUS-102',
    Capacity: 45,
    capacity: 45,
    registrationNumber: 'RJ-27-PA-9920',
    model: 'Ashok Leyland Oyster 45S',
    fuelType: 'CNG',
    driverId: 'drv_2',
    driverName: 'Sunil Verma',
    routeId: 'route_2',
    routeName: 'Fateh Sagar & MLSU Corridor (R-02)',
    shift: 'Morning',
    status: 'In Transit',
    timingStatus: 'In Transit',
    departureTime: '08:30 AM',
    expectedArrival: '09:05 AM',
    scheduledDeparture: '08:30 AM',
    delayMinutes: 0,
    isLive: true,
    currentOccupancy: 24,
    speed: 29.0,
    avgSpeed: 24.5,
    currentLat: 24.6060,
    currentLng: 73.6840,
    currentStop: 'Saheliyon Ki Bari Heritage Garden',
    nextStop: 'Panchwati Residential Stop',
    etaMinutes: 6,
    lastUpdated: new Date().toISOString(),
  },
  {
    BusID: 'bus_103',
    id: 'bus_103',
    BusNo: 'BUS-103',
    busNumber: 'BUS-103',
    Capacity: 40,
    capacity: 40,
    registrationNumber: 'RJ-27-PA-1144',
    model: 'Eicher Skyline Pro EV',
    fuelType: 'Electric',
    driverId: '',
    driverName: 'Unassigned',
    routeId: 'route_3',
    routeName: 'Hiran Magri & Tech Corridor (R-03)',
    shift: 'Afternoon',
    status: 'At Depot',
    timingStatus: 'On Time',
    departureTime: '09:00 AM',
    expectedArrival: '09:28 AM',
    scheduledDeparture: '09:00 AM',
    delayMinutes: 0,
    isLive: false,
    currentOccupancy: 0,
    speed: 0.0,
    avgSpeed: 0.0,
    currentLat: 24.5714,
    currentLng: 73.6974,
    currentStop: 'Depot Yard Slot 4',
    nextStop: 'Sector 4 Hub',
    etaMinutes: 0,
    lastUpdated: new Date().toISOString(),
  },
  {
    BusID: 'bus_104',
    id: 'bus_104',
    BusNo: 'BUS-104',
    busNumber: 'BUS-104',
    Capacity: 54,
    capacity: 54,
    registrationNumber: 'RJ-27-PA-7781',
    model: 'Volvo 9600 Multi-Axle',
    fuelType: 'Diesel',
    driverId: '',
    driverName: 'Unassigned',
    routeId: '',
    routeName: 'None',
    shift: 'None',
    status: 'Maintenance',
    timingStatus: 'Cancelled',
    departureTime: 'Cancelled',
    expectedArrival: 'Cancelled',
    scheduledDeparture: '10:00 AM',
    delayMinutes: 0,
    isLive: false,
    currentOccupancy: 0,
    speed: 0.0,
    avgSpeed: 0.0,
    currentLat: 24.5680,
    currentLng: 73.6920,
    currentStop: 'Central Maintenance Bay #2',
    nextStop: 'None',
    etaMinutes: 0,
    lastUpdated: new Date().toISOString(),
    maintenanceReason: 'Brake pad replacement & quarterly telemetry calibration'
  },
];

export const INITIAL_TRACKING = {
  bus_101: {
    BusID: 'bus_101',
    busId: 'bus_101',
    busNumber: 'BUS-101',
    departureTime: '08:15 AM',
    expectedArrival: '08:45 AM',
    timingStatus: 'In Transit',
    delayMinutes: 0,
    Latitude: 24.5880,
    currentLat: 24.5880,
    Longitude: 73.6870,
    currentLng: 73.6870,
    speed: 34.5,
    timestamp: new Date().toISOString(),
    lastUpdated: new Date().toISOString(),
    currentStop: 'Delhi Gate Central Stop',
    nextStop: 'Hathipole Market Bus Stop',
    eta: 4,
    etaMinutes: 4,
    isLive: true,
    status: 'In Transit',
  },
  bus_102: {
    BusID: 'bus_102',
    busId: 'bus_102',
    busNumber: 'BUS-102',
    departureTime: '08:30 AM',
    expectedArrival: '09:05 AM',
    timingStatus: 'In Transit',
    delayMinutes: 0,
    Latitude: 24.6060,
    currentLat: 24.6060,
    Longitude: 73.6840,
    currentLng: 73.6840,
    speed: 29.0,
    timestamp: new Date().toISOString(),
    lastUpdated: new Date().toISOString(),
    currentStop: 'Saheliyon Ki Bari Heritage Garden',
    nextStop: 'Panchwati Residential Stop',
    eta: 6,
    etaMinutes: 6,
    isLive: true,
    status: 'In Transit',
  },
  bus_103: {
    BusID: 'bus_103',
    busId: 'bus_103',
    busNumber: 'BUS-103',
    departureTime: '09:00 AM',
    expectedArrival: '09:28 AM',
    timingStatus: 'On Time',
    delayMinutes: 0,
    Latitude: 24.5714,
    currentLat: 24.5714,
    Longitude: 73.6974,
    currentLng: 73.6974,
    speed: 0.0,
    timestamp: new Date().toISOString(),
    lastUpdated: new Date().toISOString(),
    currentStop: 'Depot Yard Slot 4',
    nextStop: 'Sector 4 Hub',
    eta: 0,
    etaMinutes: 0,
    isLive: false,
    status: 'At Depot',
  },
  bus_104: {
    BusID: 'bus_104',
    busId: 'bus_104',
    busNumber: 'BUS-104',
    departureTime: 'Cancelled',
    expectedArrival: 'Cancelled',
    timingStatus: 'Cancelled',
    delayMinutes: 0,
    Latitude: 24.5680,
    currentLat: 24.5680,
    Longitude: 73.6920,
    currentLng: 73.6920,
    speed: 0.0,
    timestamp: new Date().toISOString(),
    lastUpdated: new Date().toISOString(),
    currentStop: 'Central Maintenance Bay #2',
    nextStop: 'None',
    eta: 0,
    etaMinutes: 0,
    isLive: false,
    status: 'Maintenance',
  }
};

export const INITIAL_NOTICES = [
  {
    id: 'notif_1',
    title: 'Road Resurfacing near Surajpole Flyover',
    message: 'Surajpole flyover lane 2 is under brief maintenance. Buses maintain moderate speed under 35 km/h.',
    type: 'Route Change',
    target: 'All Students',
    timestamp: 'Today, 08:00 AM',
    author: 'Transport Control Officer',
  },
  {
    id: 'notif_2',
    title: 'Advisory: Morning Drizzle & Wet Road Caution',
    message: 'Drivers are advised to maintain a safe 10-meter braking buffer during wet morning conditions.',
    type: 'General Announcement',
    target: 'Drivers',
    timestamp: 'Today, 07:30 AM',
    author: 'Safety Cell',
  },
  {
    id: 'notif_3',
    title: 'Special Shuttles for Semester Exams',
    message: 'Additional feeder buses will operate every 20 minutes from Central Railway Station next Monday.',
    type: 'General Announcement',
    target: 'All Students',
    timestamp: 'Yesterday',
    author: 'Dean of Student Affairs',
  },
];

export const INITIAL_TRIPS = [
  {
    id: 'TRP-1001',
    tripId: 'TRP-1001',
    busId: 'bus_101',
    BusID: 'bus_101',
    busNumber: 'BUS-101',
    driverId: 'drv_1',
    DriverID: 'drv_1',
    driverName: 'Ramesh Sharma',
    routeId: 'route_1',
    RouteID: 'route_1',
    routeName: 'Udaipur City Station Express (R-01)',
    startTime: '08:15 AM',
    endTime: null,
    status: 'In Transit',
    passengers: 38,
    currentStop: 'Delhi Gate Central Stop',
    nextStop: 'Hathipole Market',
    eta: '4 mins',
    date: '2026-08-09'
  },
  {
    id: 'TRP-1002',
    tripId: 'TRP-1002',
    busId: 'bus_102',
    BusID: 'bus_102',
    busNumber: 'BUS-102',
    driverId: 'drv_2',
    DriverID: 'drv_2',
    driverName: 'Sunil Verma',
    routeId: 'route_2',
    RouteID: 'route_2',
    routeName: 'Fateh Sagar & MLSU Corridor (R-02)',
    startTime: '08:30 AM',
    endTime: null,
    status: 'In Transit',
    passengers: 24,
    currentStop: 'Saheliyon Ki Bari',
    nextStop: 'Panchwati Stop',
    eta: '6 mins',
    date: '2026-08-09'
  },
  {
    id: 'TRP-0998',
    tripId: 'TRP-0998',
    busId: 'bus_101',
    BusID: 'bus_101',
    busNumber: 'BUS-101',
    driverId: 'drv_1',
    DriverID: 'drv_1',
    driverName: 'Ramesh Sharma',
    routeId: 'route_1',
    RouteID: 'route_1',
    routeName: 'Udaipur City Station Express (R-01)',
    startTime: '07:00 AM',
    endTime: '07:35 AM',
    status: 'Completed',
    passengers: 48,
    currentStop: 'Sukhadia Circle Terminal',
    nextStop: 'Trip Finished',
    eta: 'Done',
    date: '2026-08-09'
  },
  {
    id: 'TRP-0997',
    tripId: 'TRP-0997',
    busId: 'bus_102',
    BusID: 'bus_102',
    busNumber: 'BUS-102',
    driverId: 'drv_2',
    DriverID: 'drv_2',
    driverName: 'Sunil Verma',
    routeId: 'route_2',
    RouteID: 'route_2',
    routeName: 'Fateh Sagar & MLSU Corridor (R-02)',
    startTime: '07:15 AM',
    endTime: '07:55 AM',
    status: 'Completed',
    passengers: 42,
    currentStop: 'MLSU University Gate',
    nextStop: 'Trip Finished',
    eta: 'Done',
    date: '2026-08-09'
  },
  {
    id: 'TRP-0995',
    tripId: 'TRP-0995',
    busId: 'bus_104',
    BusID: 'bus_104',
    busNumber: 'BUS-104',
    driverId: 'drv_4',
    DriverID: 'drv_4',
    driverName: 'Vikram Singh',
    routeId: 'route_3',
    RouteID: 'route_3',
    routeName: 'Hiran Magri & Tech Corridor (R-03)',
    startTime: '06:30 AM',
    endTime: '07:18 AM',
    status: 'Delayed',
    passengers: 35,
    currentStop: 'Sector 4 Hub',
    nextStop: 'Goverdhan Vilas',
    eta: '18 mins delay',
    date: '2026-08-09'
  }
];

export const INITIAL_ACTIVITY_LOGS = [
  { id: 'log_1', action: 'Trip Dispatched', details: 'BUS-101 started morning run on Udaipur City Station Express (R-01)', time: '08:15 AM', category: 'Trip' },
  { id: 'log_2', action: 'Driver Assigned', details: 'Sunil Verma assigned to BUS-102 (Fateh Sagar Route)', time: '07:45 AM', category: 'Assignment' },
  { id: 'log_3', action: 'Maintenance Logged', details: 'BUS-104 moved to Central Maintenance Bay #2 for brake inspection', time: 'Yesterday, 04:30 PM', category: 'Maintenance' },
  { id: 'log_4', action: 'Notice Published', details: 'Published Road Resurfacing advisory to All Students', time: '08:00 AM', category: 'Notice' }
];

export const INITIAL_MAINTENANCE_LOGS = [
  { id: 'maint_1', busNumber: 'BUS-104', issue: 'Brake pad replacement & telemetry sensor calibration', mechanic: 'Technician Rajesh', status: 'In Maintenance', startDate: '2026-08-08', expectedReturn: '2026-08-10', cost: '₹14,500' },
  { id: 'maint_2', busNumber: 'BUS-101', issue: 'Engine oil flush and air-conditioning compressor service', mechanic: 'Technician Deepak', status: 'Resolved', startDate: '2026-08-01', expectedReturn: '2026-08-02', cost: '₹8,200' }
];

export const INITIAL_COMPLAINTS = [
  {
    id: 'CMP-1001',
    complaintId: 'CMP-1001',
    title: 'Morning Rush Hour Bus Delay',
    subject: 'Morning Rush Hour Bus Delay',
    category: 'Bus Delay',
    busNo: 'BUS-101',
    busNumber: 'BUS-101',
    description: 'Morning BUS-101 arrived 20 minutes late at Surajpole Stop causing morning lecture delay.',
    userId: 'user_student_1',
    studentId: 'STU-2026-001',
    studentName: 'Alex Johnson',
    studentEmail: 'student@smartbus.edu',
    routeName: 'Udaipur City Station Express (R-01)',
    status: 'In Progress',
    date: '12 Aug 2026',
    createdAt: 'Today, 08:45 AM',
    timestamp: 'Today, 08:45 AM',
    adminRemark: 'Traffic dispatch is investigating bottleneck near Surajpole flyover lane 2.',
    adminResponse: 'Traffic dispatch is investigating bottleneck near Surajpole flyover lane 2.'
  },
  {
    id: 'CMP-1002',
    complaintId: 'CMP-1002',
    title: 'Harsh Braking & Driver Behaviour',
    subject: 'Harsh Braking & Driver Behaviour',
    category: 'Driver Behaviour',
    busNo: 'BUS-102',
    busNumber: 'BUS-102',
    description: 'Driver applied sudden harsh braking multiple times near MLSU Gate 3.',
    userId: 'user_student_1',
    studentId: 'STU-2026-001',
    studentName: 'Alex Johnson',
    studentEmail: 'student@smartbus.edu',
    routeName: 'Fateh Sagar & MLSU Corridor (R-02)',
    status: 'Pending',
    date: '11 Aug 2026',
    createdAt: 'Yesterday, 04:30 PM',
    timestamp: 'Yesterday, 04:30 PM',
    adminRemark: '',
    adminResponse: ''
  },
  {
    id: 'CMP-1003',
    complaintId: 'CMP-1003',
    title: 'Rear Cabin AC & Window Rattle',
    subject: 'Rear Cabin AC & Window Rattle',
    category: 'Bus Condition',
    busNo: 'BUS-104',
    busNumber: 'BUS-104',
    description: 'Air conditioning cooling was insufficient in rear row seats and window panel was rattling.',
    userId: 'user_student_2',
    studentId: 'STU-2026-002',
    studentName: 'Priya Sharma',
    studentEmail: 'priya@smartbus.edu',
    routeName: 'Hiran Magri & Tech Corridor (R-03)',
    status: 'Resolved',
    date: '07 Aug 2026',
    createdAt: '07 Aug 2026',
    timestamp: '07 Aug 2026',
    resolvedAt: '08 Aug 2026, 02:15 PM',
    adminRemark: 'Bus was inspected in maintenance bay. AC compressor refrigerant refilled and window damper tightened.',
    adminResponse: 'Bus was inspected in maintenance bay. AC compressor refrigerant refilled and window damper tightened.'
  },
  {
    id: 'CMP-1004',
    complaintId: 'CMP-1004',
    title: 'Skipped Sector 4 Pick-up Stop',
    subject: 'Skipped Sector 4 Pick-up Stop',
    category: 'Route Issue',
    busNo: 'BUS-103',
    busNumber: 'BUS-103',
    description: 'Bus did not stop at Sector 4 Pick-up point despite students waiting at scheduled time.',
    userId: 'user_student_1',
    studentId: 'STU-2026-001',
    studentName: 'Alex Johnson',
    studentEmail: 'student@smartbus.edu',
    routeName: 'Hiran Magri & Tech Corridor (R-03)',
    status: 'Resolved',
    date: '05 Aug 2026',
    createdAt: '05 Aug 2026',
    timestamp: '05 Aug 2026',
    resolvedAt: '06 Aug 2026, 10:30 AM',
    adminRemark: 'Driver counselled on strictly adhering to all designated pick-up points on Route 3.',
    adminResponse: 'Driver counselled on strictly adhering to all designated pick-up points on Route 3.'
  }
];
