// Shared single source of truth for fallback in-memory state

export const inMemoryBuses = [
  { id: 1, bus_number: 'BUS-101', registration_number: 'RJ-27-PA-1001', model: 'Volvo 9400 AC Express', capacity: 52, current_occupancy: 28, fuel_type: 'Diesel', status: 'At Depot' },
  { id: 2, bus_number: 'BUS-102', registration_number: 'RJ-27-PA-1002', model: 'Tata Starbus Urban 40', capacity: 48, current_occupancy: 19, fuel_type: 'CNG', status: 'At Depot' },
  { id: 3, bus_number: 'BUS-103', registration_number: 'RJ-27-PA-1003', model: 'Ashok Leyland Lynx', capacity: 50, current_occupancy: 0, fuel_type: 'Diesel', status: 'At Depot' },
  { id: 4, bus_number: 'BUS-104', registration_number: 'RJ-27-PA-1004', model: 'Eicher Skyline Pro', capacity: 45, current_occupancy: 0, fuel_type: 'Diesel', status: 'Maintenance' },
];

export const inMemoryDrivers = [
  {
    id: 1,
    user_id: 2,
    employee_id: 'DRV-101',
    license_number: 'RJ-27-2018-00912',
    phone: '+91 94140 67890',
    status: 'Available',
    assigned_bus_id: 1,
    assigned_route_id: 1,
    shift: 'Morning',
    rating: 4.9,
    driver_name: 'Ramesh Sharma',
    driver_email: 'driver@smartbus.edu',
    bus_number: 'BUS-101',
    route_code: 'R-01',
    route_name: 'Udaipur City Station Express',
  },
  {
    id: 2,
    user_id: 3,
    employee_id: 'DRV-102',
    license_number: 'RJ-27-2019-01124',
    phone: '+91 98281 44321',
    status: 'Available',
    assigned_bus_id: 2,
    assigned_route_id: 2,
    shift: 'Morning',
    rating: 4.8,
    driver_name: 'Sunil Verma',
    driver_email: 'sunil@smartbus.edu',
    bus_number: 'BUS-102',
    route_code: 'R-02',
    route_name: 'Fateh Sagar & MLSU Corridor',
  },
];

export const inMemoryRoutes = [
  {
    id: 1,
    route_code: 'R-01',
    name: 'Udaipur City Station Express',
    start_point: 'City Railway Station',
    end_point: 'Central Campus Terminal',
    distance_km: 14.5,
    estimated_duration: '35 mins',
    status: 'Active',
  },
  {
    id: 2,
    route_code: 'R-02',
    name: 'Fateh Sagar & MLSU Corridor',
    start_point: 'Fateh Sagar Circle',
    end_point: 'North Campus Gate 2',
    distance_km: 11.2,
    estimated_duration: '28 mins',
    status: 'Active',
  },
];

export const inMemoryStops = [
  { id: 1, route_id: 1, stop_name: 'City Railway Station Terminal', latitude: 24.5714, longitude: 73.6974, stop_order: 1, scheduled_arrival: '08:00 AM' },
  { id: 2, route_id: 1, stop_name: 'Surajpole Circle', latitude: 24.578, longitude: 73.699, stop_order: 2, scheduled_arrival: '08:12 AM' },
  { id: 3, route_id: 1, stop_name: 'Delhi Gate Junction', latitude: 24.585, longitude: 73.69, stop_order: 3, scheduled_arrival: '08:22 AM' },
  { id: 4, route_id: 1, stop_name: 'Court Circle', latitude: 24.591, longitude: 73.685, stop_order: 4, scheduled_arrival: '08:29 AM' },
  { id: 5, route_id: 1, stop_name: 'Central Campus Terminal', latitude: 24.598, longitude: 73.68, stop_order: 5, scheduled_arrival: '08:35 AM' },
  { id: 6, route_id: 2, stop_name: 'Fateh Sagar Circle', latitude: 24.599, longitude: 73.675, stop_order: 1, scheduled_arrival: '08:15 AM' },
  { id: 7, route_id: 2, stop_name: 'Dewali Circle', latitude: 24.605, longitude: 73.682, stop_order: 2, scheduled_arrival: '08:23 AM' },
  { id: 8, route_id: 2, stop_name: 'MLSU Main Gate', latitude: 24.611, longitude: 73.69, stop_order: 3, scheduled_arrival: '08:33 AM' },
  { id: 9, route_id: 2, stop_name: 'North Campus Gate 2', latitude: 24.618, longitude: 73.696, stop_order: 4, scheduled_arrival: '08:43 AM' },
];

export const inMemoryTrips = [
  {
    id: 1,
    trip_code: 'TRP-1001',
    bus_id: 1,
    driver_id: 1,
    route_id: 1,
    start_time: '08:00 AM',
    end_time: '08:45 AM',
    status: 'Completed',
    passenger_count: 28,
    driver_user_id: 2,
    driver_name: 'Ramesh Sharma',
    bus_number: 'BUS-101',
    route_code: 'R-01',
    route_name: 'Udaipur City Station Express',
  },
  {
    id: 2,
    trip_code: 'TRP-1002',
    bus_id: 2,
    driver_id: 2,
    route_id: 2,
    start_time: '08:15 AM',
    end_time: '08:50 AM',
    status: 'Completed',
    passenger_count: 19,
    driver_user_id: 3,
    driver_name: 'Sunil Verma',
    bus_number: 'BUS-102',
    route_code: 'R-02',
    route_name: 'Fateh Sagar & MLSU Corridor',
  },
];

export const inMemoryTracking = [
  {
    id: 1,
    bus_id: 1,
    trip_id: 1,
    latitude: 24.585,
    longitude: 73.69,
    speed: 34.5,
    current_stop: 'Delhi Gate Junction',
    next_stop: 'Court Circle',
    eta_minutes: 7,
    is_live: 0,
    timestamp: new Date().toISOString(),
    bus_number: 'BUS-101',
    route_code: 'R-01',
    driver_name: 'Ramesh Sharma',
  },
  {
    id: 2,
    bus_id: 2,
    trip_id: 2,
    latitude: 24.605,
    longitude: 73.682,
    speed: 28.0,
    current_stop: 'Dewali Circle',
    next_stop: 'MLSU Main Gate',
    eta_minutes: 10,
    is_live: 0,
    timestamp: new Date().toISOString(),
    bus_number: 'BUS-102',
    route_code: 'R-02',
    driver_name: 'Sunil Verma',
  },
];

export const inMemoryComplaints = [
  {
    id: 1,
    user_id: 4,
    bus_id: 1,
    route_id: 1,
    subject: 'Morning Bus Delay at Surajpole',
    category: 'Bus Delay',
    description: 'Bus 101 arrived 12 minutes later than the scheduled 08:12 AM arrival time.',
    status: 'In Progress',
    priority: 'Medium',
    admin_response: 'Driver reported unexpected road maintenance at Surajpole. Route timing updated.',
    student_name: 'Alex Johnson',
    student_email: 'student@smartbus.edu',
    bus_number: 'BUS-101',
    route_code: 'R-01',
  },
  {
    id: 2,
    user_id: 5,
    bus_id: 2,
    route_id: 2,
    subject: 'AC Temperature High in Afternoon',
    category: 'Comfort & Maintenance',
    description: 'Air conditioning in BUS-102 was inadequate during the afternoon return trip.',
    status: 'Resolved',
    priority: 'Low',
    admin_response: 'Technician inspected AC compressor and refilled refrigerant.',
    student_name: 'Priya Sharma',
    student_email: 'priya@smartbus.edu',
    bus_number: 'BUS-102',
    route_code: 'R-02',
  },
];

export const inMemoryNotices = [
  {
    id: 1,
    title: 'Route R-01 Morning Timing Adjustment',
    message: 'Please note that Route 1 will run 5 minutes earlier starting next Monday due to road work near Surajpole.',
    type: 'Schedule Notice',
    target: 'All Students',
    created_by: 1,
    creator_name: 'Dr. Arthur Vance (Fleet Director)',
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    title: 'Digital Campus Transit Pass Requirement',
    message: 'All students are requested to keep their SmartBus Digital Pass open on their phones when boarding campus buses.',
    type: 'General Announcement',
    target: 'All Students',
    created_by: 1,
    creator_name: 'Dr. Arthur Vance (Fleet Director)',
    created_at: new Date().toISOString(),
  },
];
